gallery/urls.py
from django.urls import path
from . import views
from .views import GalleryView, GalleryDetail

app_name = 'gallery'

urlpatterns = [
    path('<slug:slug>/edit_comment/<int:comment_id>',
         views.comment_edit, name='comment_edit'),
    path('<slug:slug>/delete_comment/<int:comment_id>',
         views.comment_delete, name='comment_delete'),
    path('', GalleryView.as_view(), name='gallery'),
    path('<slug:slug>/', GalleryDetail.as_view(), name='gallery_detail'),
    path('<slug:slug>', views.PostLike.as_view(), name='post-like'),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home_view, name='home'),
    
]

walking_wainwrights/urls.py
from django.contrib import admin
from django.urls import path, include
from routes import views as routes

urlpatterns = [
    path('contact/', include('contact.urls'), name='contact'),
    path('', include('about.urls'), name='about'),
    path('gallery/', include('gallery.urls'), name='gallery'),
    path('summernote/', include('django_summernote.urls')),
    path('routes/', include('routes.urls'), name='routes'),
    path('admin/', admin.site.urls),
    path('accounts/', include("allauth.urls")),
]

gallery/models.py
from django.db import models
from cloudinary.models import CloudinaryField
from cloudinary.forms import CloudinaryFileField
from django.contrib.auth.models import User
from routes.models import Comment, Route
from django.template.defaultfilters import slugify

STATUS = ((0, "Draft"), (1, "Published"))


class Gallery(models.Model):
    title = models.CharField(max_length=255, blank=True)
    slug = models.SlugField(max_length=100)
    uploaded_at = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    status = models.IntegerField(choices=STATUS, default=0)
    flagged = models.BooleanField(default=False)
    img_detail = models.TextField(max_length=50)
    feature_img = models.URLField(blank=True, null=True)
    likes = models.ManyToManyField(
        User, related_name='image_like', blank=True)

    class Meta:
        ordering = ["-uploaded_at"]

    def __str__(self):
        return self.title

    def number_of_likes(self):
        return self.likes.count()

    def save(self, *args, **kwargs):
        if self.title:
            self.slug = slugify(self.title)
        super(Gallery, self).save(*args, **kwargs)


class Comment(models.Model):
    post = models.ForeignKey(Gallery, on_delete=models.CASCADE,
                             related_name="comments")
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="gallery_comments"
    )
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    approved = models.BooleanField(default=False)
    flagged = models.BooleanField(default=False)
    feature_img = models.URLField(blank=True, null=True)

    class Meta:
        ordering = ["created_on"]

    def __str__(self):
        return f"Comment {self.id} by {self.author}"

gallery/forms.py
from .models import Comment, Gallery
from django import forms
from cloudinary.forms import CloudinaryFileField


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('body',)


class GalleryForm(forms.ModelForm):

    class Meta:
        model = Gallery
        fields = ['title', 'img_detail']

gallery/views.py
from django.core.paginator import Paginator
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, reverse
from django.views import View
from django.contrib import messages

from .models import Gallery, Comment
from .forms import CommentForm, GalleryForm


class GalleryView(View):
    def get(self, request):
        feature_img = Gallery.objects.filter(status=1)
        paginator = Paginator(feature_img, 4)
        page_number = request.GET.get('page')
        page_object = paginator.get_page(page_number)
        gallery_form = GalleryForm()
        return render(request, 'gallery/gallery.html', {
            'page_object': page_object,
            'gallery_form': gallery_form,
        })

    def post(self, request):
        gallery_form = GalleryForm(request.POST, request.FILES)
        if gallery_form.is_valid():
            gallery = gallery_form.save(commit=False)
            gallery.author = request.user
            gallery.feature_img = request.POST.get('feature_img')
            gallery.save()
            messages.success(request, 'Gallery uploaded successfully!')
            feature_img = Gallery.objects.filter(status=1)
            paginator = Paginator(feature_img, 4)
            page_number = request.GET.get('page')
            page_object = paginator.get_page(page_number)

            return render(request, 'gallery/gallery.html', {
                'page_object': page_object,
                'gallery_form': GalleryForm(),
            })
        else:
            messages.error(
                request, 'Error uploading gallery. Please try again.'
            )
            return render(request, 'gallery/gallery.html', {
                'page_object': page_object,
                'gallery_form': GalleryForm(),
            })


class GalleryDetail(View):
    def get(self, request, slug):
        gallery = self.get_gallery(slug)
        comments = gallery.comments.all().order_by("-created_on")
        comment_count = gallery.comments.filter(approved=True).count()
        liked = gallery.likes.filter(id=request.user.id).exists()

        return render(request, 'gallery/gallery_detail.html', {
            'gallery': gallery,
            'comments': comments,
            "gallery_comments": False,
            "liked": liked,
            'comment_count': comment_count,
            'comment_form': CommentForm(),
        })

    def post(self, request, slug):
        gallery = self.get_gallery(slug)
        comments = gallery.comments.all().order_by("-created_on")
        comment_count = gallery.comments.filter(approved=True).count()
        comment_form = CommentForm(data=request.POST)
        liked = gallery.likes.filter(id=request.user.id).exists()

        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.author = request.user
            comment.post = gallery
            comment.feature_img = request.POST.get('feature_img')
            comment.save()
            messages.add_message(
                request, messages.SUCCESS, 'Comment submitted!'
            )
        else:
            messages.add_message(
                request, messages.ERROR, 'Error submitting comment!'
            )

        return render(request, 'gallery/gallery_detail.html', {
            'gallery': gallery,
            'comments': comments,
            "gallery_comments": True,
            "liked": liked,
            'comment_count': comment_count,
            'comment_form': CommentForm(),
        })

    def get_gallery(self, slug):
        return get_object_or_404(Gallery, slug=slug)


class PostLike(View):
    def post(self, request, slug):
        gallery = get_object_or_404(Gallery, slug=slug)
        if gallery.likes.filter(id=request.user.id).exists():
            gallery.likes.remove(request.user)
        else:
            gallery.likes.add(request.user)
        return HttpResponseRedirect(
            reverse('gallery:gallery_detail', args=[slug])
        )


def comment_edit(request, slug, comment_id):
    if request.method == "POST":
        gallery = get_object_or_404(
            Gallery.objects.filter(status=1), slug=slug
        )
        comment = get_object_or_404(Comment, pk=comment_id)
        comment_form = CommentForm(data=request.POST, instance=comment)

        if comment_form.is_valid() and comment.author == request.user:
            comment = comment_form.save(commit=False)
            comment.post = gallery
            comment.approved = False
            comment.save()
            messages.add_message(request, messages.SUCCESS, 'Comment Updated!')
        else:
            messages.add_message(
                request, messages.ERROR, 'Error updating comment!'
            )

    return HttpResponseRedirect(reverse('gallery:gallery_detail', args=[slug]))


def comment_delete(request, slug, comment_id):
    gallery = get_object_or_404(Gallery.objects.filter(status=1), slug=slug)
    comment = get_object_or_404(Comment, pk=comment_id)

    if comment.author == request.user:
        comment.delete()
        messages.add_message(request, messages.SUCCESS, 'Comment deleted!')
    else:
        messages.add_message(
            request, messages.ERROR, 'You can only delete your own comments!'
        )

    return HttpResponseRedirect(reverse('gallery:gallery_detail', args=[slug]))

gallery/templates/gallery/gallery.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
{% load crispy_forms_tags %}

<script src="https://widget.cloudinary.com/v2.0/global/all.js"></script>

<div class="container">
    {% if messages %}
    <div class="alert alert-success" role="alert">
        {% for message in messages %}
        {{ message }}
        {% endfor %}
    </div>
    {% endif %}

    <div class="row row-cols-1 row-cols-md-2 g-4 gallery-grid">
        {% for gallery in page_object %}
        <div class="col-md-6 mb-4">
            <div class="card gallery-container">
                <a href="{% url 'gallery:gallery_detail' slug=gallery.slug %}">
                    <img src="{{ gallery.feature_img }}" class="card-img-top" alt="{{ gallery.title }}">
                </a>
                <div class="card-body">
                    <a href="{% url 'gallery:gallery_detail' slug=gallery.slug %}">
                        <h5 class="card-title text-center">{{ gallery.title }}</h5>
                    </a>
                    <p class="card-text">{{ gallery.img_detail }}</p>
                    <p class="card-text"><small class="text-muted">{{ gallery.uploaded_at }}</small></p>
                    <p class="card-text"><small class="text-muted">Created by: {{ gallery.author }}</small></p>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>

    <div class="pagination text-center">
        <div class="d-flex justify-content-between">
            {% if page_object.has_previous %}
            <a href="?page=1" class="btn btn-secondary text-light text-decoration-none mr-2">&laquo; first</a>
            <a href="?page={{ page_object.previous_page_number }}" class="btn btn-secondary text-light text-decoration-none">previous</a>
            {% endif %}
            <span>
                <button class="btn btn-secondary mr-2 ml-2 page-of" disabled>Page {{ page_object.number }} of {{ page_object.paginator.num_pages }}.</button>
            </span>
            {% if page_object.has_next %}
            <a href="?page={{ page_object.next_page_number }}" class="btn btn-secondary text-light text-decoration-none">next</a>
            <a href="?page={{ page_object.paginator.num_pages }}" class="btn btn-secondary text-light text-decoration-none ml-2">last &raquo;</a>
            {% endif %}
        </div>
    </div>

    <div class="card-container">
        <div class="card">
            <div class="card-body">
                {% if user.is_authenticated %}
                <h3>Post a Photo:</h3>
                <p>Upload your photo, give it a title and description and hit Submit.</p>
                <p>Posting as: {{ user.username }}</p>
                <form id="GalleryForm" method="post" style="margin-top: 1.3em;">
                    {{ gallery_form | crispy }}
                    {% csrf_token %}
                    <button type="button" id="upload_widget_opener" class="btn btn-primary">Upload Image</button>
                    <input type="hidden" id="id_feature_img" name="feature_img">
                    <button id="submitButton" type="submit" class="btn btn-signup btn-lg">Submit</button>
                </form>
                {% else %}
                <p>You must be logged in to post a photo.</p>
                {% endif %}
            </div>
        </div>
    </div>
</div>



{% endblock %}
{% block extras %}
<script src="{% static 'js/image.js' %}"></script>
{% endblock %}

gallery/templates/gallery/gallery_detail.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
{% load crispy_forms_tags %}

<div class="container">
{% if messages %}
<div class="container">
    <div class="alert alert-success" role="alert">
        {% for message in messages %}
        {{ message }}
        {% endfor %}
    </div>
</div>
{% endif %}

<div class="container">
    <br>
    <h1 class="white-text">{{ gallery.title }}</h1>
    <img src="{{ gallery.feature_img }}" class="card-img-top" alt="...">
    <br>
    <hr>
    <div>
        {% if user.is_authenticated %}
        <form class="d-inline" action="{% url 'gallery:post-like' gallery.slug %}" method="POST">
            {% csrf_token %}
            {% if liked %}
            <button type="submit" class="like-btn" name="blogpost_id" value="{{post.slug}}"><i class="fas fa-heart fa-1x"></i></button>
            {% else %}
            <button type="submit" class="like-btn" name="blogpost_id" value="{{post.slug}}"><i class="far fa-heart fa-1x"></i></button>
            {% endif %}
        </form>
        {% else %}
        <p>You must be logged in to like this post.</p>
        <span class="like-btn"><i class="far fa-heart fa-1x"></i></span>
        {% endif %} 
        <span class="text-secondary">{{ gallery.number_of_likes }} </span>
    </div>
    <hr>
    <br>
    <p class="white-text">{{ gallery.img_detail }}</p>
    <p class="white-text">{{ gallery.uploaded_at }}</p>
    <p class="white-text">Created by: {{ gallery.author }}</p>
    <br>

    <div class="container">
        <div class="row">
            <div class="col-md-8 card mb-4 mt-3 ml-0">
                {% with comment_count as total_comments %}
                <strong class="text-secondary comment-count"><i class="far fa-comments"></i>
                {{ total_comments }}</strong>
                {% endwith %}
                <h3 class="comment-title">Comments:</h3>
                <div class="card-body">
                    {% for comment in comments %}
                    <div class="p-2 comments{% if not comment.approved and comment.author == user %} faded{% elif not comment.approved %} d-none{% endif %} comment-border">
                        <p class="font-weight-bold comment-author">
                            {{ comment.author }}
                            <span class="font-weight-normal comment-date">
                                {{ comment.created_on }}
                            </span> wrote:
                        </p>
                        <div id="comment{{ comment.id }}" class="comment-body">
                            {{ comment.body | linebreaks }}
                        </div>
                        {% if not comment.approved and comment.author == user %}
                        <p class="approval">This comment is awaiting approval</p>
                        {% endif %}
                        {% if user.is_authenticated and comment.author == user %}
                        <button class="btn btn-delete" comment_id="{{ comment.id }}">Delete</button>
                        <button class="btn btn-edit" comment_id="{{ comment.id }}">Edit</button>
                        {% endif %}
                    </div>
                    {% endfor %}
                </div>
            </div>
            <div class="col-md-4 card mb-4 mt-3">
                <div class="card-body">
                    {% if commented %}
                        <div class="alert alert-success" role="alert" class="comment-alert">
                            Your comment is awaiting approval
                        </div>
                    {% else %}
                    {% if user.is_authenticated %}
                        <h3 class="comment-prompt">Leave a comment:</h3>
                        <p class="comment-info">Posting as: {{ user.username }}</p>
                        <form id="commentForm" method="post" class="comment-form">
                            {{ comment_form | crispy }}
                            {% csrf_token %}
                            <button id="submitButton" type="submit" class="btn btn-signup btn-lg btn-secondary text-light text-decoration-none">Submit</button>
                        </form>
                    {% else %}
                        <p class="comment-info">You must be logged in to comment on this post.</p>
                    {% endif %}
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Delete confirmation modal -->
<div class="modal fade" id="deleteModal" tabindex="-1"
 aria-labelledby="deleteModalLabel" aria-hidden="true">
 <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title"
          id="deleteModalLabel">Delete comment?</h5>
        <button type="button" class="btn-close"
          data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        Are you sure you want to delete your comment?
        This action cannot be undone.
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary"
          data-dismiss="modal">Close</button>
        <a id="deleteConfirm" href="#" class="btn
          btn-danger">Delete</a>
      </div>
    </div>
 </div>
</div>
</div>

{% endblock content %}
{% block extras %}
<script src="{% static 'js/comment.js' %}"></script>
{% endblock %}