home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home_view, name='home'),
    
]

routes/urls.py
from django.urls import path
from .views import Routes, RoutesDetail, PostLike
from . import views

app_name = 'routes'

urlpatterns = [
    path('<slug:slug>/edit_comment/<int:comment_id>',
         views.comment_edit, name='comment_edit'),
    path('<slug:slug>/delete_comment/<int:comment_id>',
         views.comment_delete, name='comment_delete'),
    path('', Routes.as_view(), name='routes'),
    path('<slug:slug>/', RoutesDetail.as_view(), name='routes_detail'),
    path('<slug:slug>', views.PostLike.as_view(), name='post-like'),
]

walking_wainwrights/urls.py
from django.contrib import admin
from django.urls import path, include
from routes import views as routes

urlpatterns = [
    path('contact/', include('contact.urls'), name='contact'),
    path('', include('about.urls'), name='about'),
    path('gallery/', include('gallery.urls'), name='gallery'),
    path('summernote/', include('django_summernote.urls')),
    path('routes/', include('routes.urls'), name='routes'),
    path('admin/', admin.site.urls),
    path('accounts/', include("allauth.urls")),
]

routes/models.py
from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField
from django.utils.html import format_html
from django.template.defaultfilters import slugify

STATUS = ((0, "Draft"), (1, "Published"))
DIFFICULTY_RATING = [
    (1, '1'),
    (2, '2'),
    (3, '3'),
    (4, '4'),
    (5, '5'),
]


class Route(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100, unique=True)
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="route_posts"
    )
    content = models.TextField()
    os_url = models.URLField(blank=True, null=True)
    created_on = models.DateTimeField(auto_now_add=True)
    post_edit = models.DateTimeField(auto_now=True)
    difficulty_rating = models.IntegerField(
        choices=DIFFICULTY_RATING,
        default=1
    )
    likes = models.ManyToManyField(
        User, related_name='blogpost_likes', blank=True
    )
    status = models.IntegerField(choices=STATUS, default=0)
    flagged = models.BooleanField(default=False)
    feature_img = CloudinaryField('image', default='placeholder')
    route_video = models.URLField(blank=True, null=True)

    class Meta:
        ordering = ["-created_on"]

    def __str__(self):
        return self.title

    def snippet(self):
        return self.content[:100]

    def number_of_likes(self):
        return self.likes.count()

    def difficulty_icon(self):
        icon_class = 'fa-solid fa-shoe-prints'
        icons_html = ''.join([
            f'<i class="fas {icon_class}"></i> | '
            for _ in range(self.difficulty_rating)
        ])

        return format_html(icons_html)


class Comment(models.Model):
    post = models.ForeignKey(
        Route,
        on_delete=models.CASCADE,
        related_name="comments"
    )
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="comments"
    )
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    approved = models.BooleanField(default=False)
    flagged = models.BooleanField(default=False)
    feature_img = CloudinaryField('image', default='placeholder')

    class Meta:
        ordering = ["created_on"]

    def __str__(self):
        return f"Comment {self.id} by {self.author}"

routes/forms.py
from .models import Comment
from django import forms


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)

routes/admin.py
from django.contrib import admin
from django_summernote.admin import SummernoteModelAdmin
from .models import Route, Comment


@admin.register(Route)
class PostAdmin(SummernoteModelAdmin):
    list_display = ('title', 'slug', 'status', 'created_on', 'flagged',)
    search_fields = ['title', 'content', 'flagged', ]
    list_filter = ('status', 'created_on', 'flagged', )

    def publish_posts(self, request, queryset):
        queryset.update(status=1)
    publish_posts.short_description = "Publish selected posts"

    def flagged_posts(self, request, queryset):
        queryset.update(flagged=True)
    flagged_posts.short_description = "Flag selected posts"
    actions = [publish_posts, flagged_posts]


@admin.register(Comment)
class CommentAdmin(admin.ModelAdmin):
    list_display = (
        'author', 'body', 'post', 'created_on', 'approved', 'flagged',
    )
    list_filter = ('approved', 'created_on')
    search_fields = ('author', 'email', 'body')

    def approve_comment(self, request, queryset):
        queryset.update(approved=1)
    approve_comment.short_description = "Approve selected comments"

    def flagged_comment(self, request, queryset):
        queryset.update(flagged=True)
    flagged_comment.short_description = "Flag selected comment"
    actions = [approve_comment, flagged_comment]

routes/apps.py
from django.apps import AppConfig


class RoutesConfig(AppConfig):
    default_auto_field = 'django.db.models.BigAutoField'
    name = 'routes'

routes/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404, reverse
from django.views import View
from .models import Route, Comment
from .forms import CommentForm
from django.contrib import messages
from django.http import HttpResponseRedirect


class Routes(View):
    def get(self, request):
        route_list = Route.objects.filter(status=1)
        paginator = Paginator(route_list, 4)
        page_number = request.GET.get('page')
        page_object = paginator.get_page(page_number)
        return render(
            request, 'routes/routes.html', {'page_object': page_object}
        )


class RoutesDetail(View):
    def get(self, request, slug):
        route = get_object_or_404(Route, slug=slug)
        comments = route.comments.all().order_by("-created_on")
        comment_count = route.comments.filter(approved=True).count()
        liked = False
        if route.likes.filter(id=self.request.user.id).exists():
            liked = True

        return render(
            request, 'routes/routes_detail.html',
            {
                'route': route,
                'comments': comments,
                "commented": False,
                "liked": liked,
                'comment_count': comment_count,
                'comment_form': CommentForm(),
            }
        )

    def post(self, request, slug):
        route = get_object_or_404(Route, slug=slug)
        comments = route.comments.all().order_by("-created_on")
        comment_count = route.comments.filter(approved=True).count()
        comment_form = CommentForm(data=request.POST)
        liked = False
        if route.likes.filter(id=self.request.user.id).exists():
            liked = True

        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.author = request.user
            comment.post = route
            comment.save()
        else:
            comment_form = CommentForm()

        return render(
            request, 'routes/routes_detail.html',
            {
                'route': route,
                'comments': comments,
                "commented": True,
                "liked": liked,
                'comment_count': comment_count,
                'comment_form': CommentForm(),
            }
        )


class PostLike(View):
    def post(self, request, slug):
        route = get_object_or_404(Route, slug=slug)

        if route.likes.filter(id=request.user.id).exists():
            route.likes.remove(request.user)
        else:
            route.likes.add(request.user)
        return HttpResponseRedirect(
            reverse('routes:routes_detail', args=[slug])
        )


def comment_edit(request, slug, comment_id):
    """
    view to edit comments
    """
    if request.method == "POST":

        queryset = Route.objects.filter(status=1)
        route = get_object_or_404(queryset, slug=slug)
        comment = get_object_or_404(Comment, pk=comment_id)
        comment_form = CommentForm(data=request.POST, instance=comment)

        if comment_form.is_valid() and comment.author == request.user:
            comment = comment_form.save(commit=False)
            comment.post = route
            comment.approved = False
            comment.save()
            messages.add_message(request, messages.SUCCESS, 'Comment Updated!')
        else:
            messages.add_message(
                request, messages.ERROR, 'Error updating comment!'
            )

    return HttpResponseRedirect(reverse('routes:routes_detail', args=[slug]))


def comment_delete(request, slug, comment_id):
    """
    view to delete comment
    """
    queryset = Route.objects.filter(status=1)
    route = get_object_or_404(queryset, slug=slug)
    comment = get_object_or_404(Comment, pk=comment_id)

    if comment.author == request.user:
        comment.delete()
        messages.add_message(request, messages.SUCCESS, 'Comment deleted!')
    else:
        messages.add_message(
            request, messages.ERROR, 'You can only delete your own comments!'
        )

    return HttpResponseRedirect(reverse('routes:routes_detail', args=[slug]))

routes/templates/routes/routes.html
{% extends 'base.html' %}
{% block content %}
<main>
    <section class="container">
        <h1 class="page-heading">Routes</h1>
        <div class="row row-cols-1 row-cols-md-2 g-4">
            {% for route in page_object %}
            <article class="col-md-6 mb-4">
                <div class="card route-card">
                    <a href="{% url 'routes:routes_detail' slug=route.slug %}">
                        <img src="{{ route.feature_img.url }}" class="card-img-top route-card-image" alt="{{ route.title }}">
                    </a>
                    <div class="card-body">
                        <a href="{% url 'routes:routes_detail' slug=route.slug %}">
                            <h5 class="card-title text-center">{{ route.title }}</h5>
                        </a>
                        <p class="card-text">{{ route.snippet | safe }} ... </p>
                        <p class="card-text"><small class="text-muted">{{ route.created_on }}</small></p>
                        <p class="card-text"><small class="text-muted">Created by: {{ route.author }}</small></p>
                    </div>
                </div>
            </article>
            {% endfor %}
        </div>

        <nav class="pagination text-center">
            <div class="d-flex justify-content-between">
                {% if page_object.has_previous %}
                <a href="?page=1" class="btn btn-secondary text-light text-decoration-none mr-2">&laquo; first</a>
                <a href="?page={{ page_object.previous_page_number }}" class="btn btn-secondary text-light text-decoration-none">previous</a>
                {% endif %}
                <span>
                    <button class="btn btn-secondary mr-2 ml-2 page-of" disabled>Page {{ page_object.number }} of {{ page_object.paginator.num_pages }}.</button>
                </span>
                {% if page_object.has_next %}
                <a href="?page={{ page_object.next_page_number }}" class="btn btn-secondary text-light text-decoration-none">next</a>
                <a href="?page={{ page_object.paginator.num_pages }}" class="btn btn-secondary text-light text-decoration-none ml-2">last &raquo;</a>
                {% endif %}
            </div>
        </nav>
    </section>
</main>
{% endblock %}

routes/templates/routes/routes_detail.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
{% load crispy_forms_tags %}

<div class="container">
{% if messages %}
<div class="container">
    <div class="alert alert-success" role="alert">
        {% for message in messages %}
        {{ message }}
        {% endfor %}
    </div>
</div>
{% endif %}

<div class="container routes-container">
    <h1>{{ route.title }}</h1>
    <script src="{{ route.os_url }}"></script>
    <br>
    <hr>
    <h6>
        Difficulty Rating:
    </h6>
    <p>
        {{ route.difficulty_icon }}
        {{ route.difficulty_rating }}/5
    </p> 
    <br>
    <div>
        {% if user.is_authenticated %}
        <form class="d-inline" action="{% url 'routes:post-like' route.slug %}" method="POST">
            {% csrf_token %}
            {% if liked %}
            <button type="submit" class="like-btn" value="{{post.slug}}"><i class="fas fa-heart fa-1x"></i></button>
            {% else %}
            <button type="submit" class="like-btn" value="{{post.slug}}"><i class="far fa-heart fa-1x"></i></button>
            {% endif %}
        </form>
        {% else %}
        <p>You must be logged in to like this post.</p>
        <span class="like-btn"><i class="far fa-heart fa-1x"></i></span>
        {% endif %}  
        <span class="text-secondary routes-counter">{{ route.number_of_likes }} </span> 
    </div>
    <br>
    <hr>
    <p class ="route-body">{{ route.content | safe }}</p>
    <p>{{ route.created_on }}</p>
    <p>Created by: {{ route.author }}</p>
    <br>
    <hr>
    <br>
    <div class="iframe-container">
        <iframe width="560" height="315" src="{{ route.route_video }}" title="YouTube video player" 
        allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" 
        referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
    </div>
</div>
<br>
<hr>
<div class="container">
    <div class="row">
        <div class="col-md-8 card mb-4 mt-3 ml-0">
            {% with comment_count as total_comments %}
            <strong class="text-secondary comment-count"><i class="far fa-comments"></i>
            {{ total_comments }}</strong>
            {% endwith %}
            <h3 class="comment-title">Comments:</h3>
            <div class="card-body">
                {% for comment in comments %}
                <div class="p-2 comments{% if not comment.approved and comment.author == user %} faded{% elif not comment.approved %} d-none{% endif %}" class="comment-border">
                    <p class="font-weight-bold">
                        {{ comment.author }}
                        <span class="font-weight-normal">
                            {{ comment.created_on }}
                        </span> wrote:
                    </p>
                    <div id="comment{{ comment.id }}" class="comment-body">
                        {{ comment.body | linebreaks }}
                    </div>
                    {% if not comment.approved and comment.author == user %}
                    <p class="approval">This comment is awaiting approval</p>
                    {% endif %}
                    {% if user.is_authenticated and comment.author == user %}
                    <button class="btn btn-delete" comment_id="{{ comment.id }}">Delete</button>
                    <button class="btn btn-edit" comment_id="{{ comment.id }}">Edit</button>
                    {% endif %}
                </div>
                {% endfor %}
            </div>
        </div>
        <div class="col-md-4 card mb-4 mt-3">
            <div class="card-body">
                {% if commented %}
                    <div class="alert alert-success" role="alert" class="comment-alert">
                        Your comment is awaiting approval
                    </div>
                {% else %}
                {% if user.is_authenticated %}
                    <h3 class="comment-prompt">Leave a comment:</h3>
                    <p class="comment-info">Posting as: {{ user.username }}</p>
                    <form id="commentForm" method="post" class="comment-form">
                        {{ comment_form | crispy }}
                        {% csrf_token %}
                        <button id="submitButton" type="submit" class="btn btn-signup btn-lg btn-secondary text-light text-decoration-none">Submit</button>
                    </form>
                {% else %}
                    <p class="comment-info">You must be logged in to comment on this post.</p>
                {% endif %}
                {% endif %}
            </div>
        </div>
    </div>
</div>

<!-- Delete confirmation modal -->
<div class="modal fade" id="deleteModal" tabindex="-1"
 aria-labelledby="deleteModalLabel" aria-hidden="true">
 <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title"
          id="deleteModalLabel">Delete comment?</h5>
        <button type="button" class="btn-close"
          data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        Are you sure you want to delete your comment?
        This action cannot be undone.
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary"
          data-dismiss="modal">Close</button>
        <a id="deleteConfirm" href="#" class="btn
          btn-danger">Delete</a>
      </div>
    </div>
 </div>
</div>

</div>
{% endblock content %}

{% block extras %}
<script src="{% static 'js/comment.js' %}"></script>
{% endblock %}