about/urls.py
from django.urls import path
from . import views
from .views import AboutView, wainwrights, contact

app_name = 'about'

urlpatterns = [
    path('', AboutView.as_view(), name='about'),
    path('wainwrights/', wainwrights, name='wainwrights'),
    path('contact/', contact, name='contact'),
]

gallery/urls.py
from django.urls import path
from . import views
from .views import GalleryView, GalleryDetail

app_name = 'gallery'

urlpatterns = [
    path('<slug:slug>/edit_comment/<int:comment_id>',
         views.comment_edit, name='comment_edit'),
    path('<slug:slug>/delete_comment/<int:comment_id>',
         views.comment_delete, name='comment_delete'),
    path('', GalleryView.as_view(), name='gallery'),
    path('<slug:slug>/', GalleryDetail.as_view(), name='gallery_detail'),
    path('<slug:slug>', views.PostLike.as_view(), name='post-like'),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home_view, name='home'),
    
]

routes/urls.py
from django.urls import path
from .views import Routes, RoutesDetail, PostLike
from . import views

app_name = 'routes'

urlpatterns = [
    path('<slug:slug>/edit_comment/<int:comment_id>',
         views.comment_edit, name='comment_edit'),
    path('<slug:slug>/delete_comment/<int:comment_id>',
         views.comment_delete, name='comment_delete'),
    path('', Routes.as_view(), name='routes'),
    path('<slug:slug>/', RoutesDetail.as_view(), name='routes_detail'),
    path('<slug:slug>', views.PostLike.as_view(), name='post-like'),
]

walking_wainwrights/urls.py
from django.contrib import admin
from django.urls import path, include
from routes import views as routes

urlpatterns = [
    path('contact/', include('contact.urls'), name='contact'),
    path('', include('about.urls'), name='about'),
    path('gallery/', include('gallery.urls'), name='gallery'),
    path('summernote/', include('django_summernote.urls')),
    path('routes/', include('routes.urls'), name='routes'),
    path('admin/', admin.site.urls),
    path('accounts/', include("allauth.urls")),
]

walking_wainwrights/templates/base.html
{% load static %}

{% url 'account_login' as login_url %}
{% url 'account_signup' as signup_url %}
{% url 'account_logout' as logout_url %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Walking the Wainwrights</title>
    <!-- Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
    <!-- Font Awesome for Social Icons -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="{% static 'fontawesome_free/css/all.min.css' %}" rel="stylesheet" type="tex/css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg sticky-navbar">
        <a class="navbar-brand text-light" href="{% url 'about:about' %}">Walking the Wainwrights</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" 
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon text"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item {% if request.path == '/' %}active{% endif %}">
                    <a class="nav-link" href="{% url 'about:about' %}">About</a>
                </li>
                <li class="nav-item {% if request.path == '/routes/' %}active{% endif %}">
                    <a class="nav-link" href="{% url 'routes:routes' %}">Routes</a>
                </li>
                <li class="nav-item {% if request.path == '/gallery/' %}active{% endif %}">
                    <a class="nav-link" href="{% url 'gallery:gallery' %}">Gallery</a>
                </li>
                <!--login/out etc-->
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link {% if request.path == logout_url %}active{% endif %}" aria-current="page" href="{% url 'account_logout' %}">Logout</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link {% if request.path == signup_url %}active{% endif %}" aria-current="page" href="{% url 'account_signup' %}">Register</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% if request.path == login_url %}active{% endif %}" aria-current="page" href="{% url 'account_login' %}">Login</a>
                </li>
                {% endif %}
            </ul>
            <span class="navbar-text ml-auto logged-in">
                {% if user.is_authenticated %}
                Welcome {{ user }} you are logged in.
                {% else %}
                You are not logged in
                {% endif %}
            </span>
        </div>
    </nav>
    <!-- Page Content -->
    
        {% block content %}
        {% endblock %}
   

    <!-- Sticky Footer with Social Media Links -->
    <footer class="footer text-center">
        <div class="container">
            <section class="mb-1">
                <h4>Social Media Links</h4>
                <!-- Social Media Links -->
                <a href="https://www.facebook.com/" target="_blank" role="button"><i class="fab fa-facebook-f" name="facebook"></i></a>
                <a href="http://www.twitter.com" target="_blank" role="button"><i class="fab fa-twitter" name="twitter"></i></a>
                <a href="http://www.instagram.com" target="_blank" role="button"><i class="fab fa-instagram" name="instagram"></i></a>
                <a href="http://www.linkedin.com" target="_blank" role="button"><i class="fab fa-linkedin-in" name="linkedin"></i></a>
            </section>
        </div>
        <div class="text-center">
            <p class="copyright">© 2024 Copyright: Martin Bradbury</p>
        </div>
    </footer>

    <!-- Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    {% block extras %}
    {% endblock %}
</body>
</html>