about/urls.py
from django.urls import path
from . import views
from .views import AboutView, wainwrights, contact

app_name = 'about'

urlpatterns = [
    path('', AboutView.as_view(), name='about'),
    path('wainwrights/', wainwrights, name='wainwrights'),
    path('contact/', contact, name='contact'),
]

contact/urls.py
from django.urls import path
from . import views

app_name = 'contact'

urlpatterns = [
    path('', views.contact_view, name='contact'),
]

gallery/urls.py
from django.urls import path
from . import views
from .views import GalleryView, GalleryDetail

app_name = 'gallery'

urlpatterns = [
    path('<slug:slug>/edit_comment/<int:comment_id>',
         views.comment_edit, name='comment_edit'),
    path('<slug:slug>/delete_comment/<int:comment_id>',
         views.comment_delete, name='comment_delete'),
    path('', GalleryView.as_view(), name='gallery'),
    path('<slug:slug>/', GalleryDetail.as_view(), name='gallery_detail'),
    path('<slug:slug>', views.PostLike.as_view(), name='post-like'),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home_view, name='home'),
    
]

routes/urls.py
from django.urls import path
from .views import Routes, RoutesDetail, PostLike
from . import views

app_name = 'routes'

urlpatterns = [
    path('<slug:slug>/edit_comment/<int:comment_id>',
         views.comment_edit, name='comment_edit'),
    path('<slug:slug>/delete_comment/<int:comment_id>',
         views.comment_delete, name='comment_delete'),
    path('', Routes.as_view(), name='routes'),
    path('<slug:slug>/', RoutesDetail.as_view(), name='routes_detail'),
    path('<slug:slug>', views.PostLike.as_view(), name='post-like'),
]

walking_wainwrights/urls.py
from django.contrib import admin
from django.urls import path, include
from routes import views as routes

urlpatterns = [
    path('contact/', include('contact.urls'), name='contact'),
    path('', include('about.urls'), name='about'),
    path('gallery/', include('gallery.urls'), name='gallery'),
    path('summernote/', include('django_summernote.urls')),
    path('routes/', include('routes.urls'), name='routes'),
    path('admin/', admin.site.urls),
    path('accounts/', include("allauth.urls")),
]

about/models.py
from django.db import models
from cloudinary.models import CloudinaryField

COMPLETED = ((0, "Not Complete"), (1, "Completed"))


class About(models.Model):
    title = models.CharField(max_length=100)
    profile_img = CloudinaryField('image', default='placeholder')
    content = models.TextField()
    updated_on = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class Wainwright(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    wainwright_img = CloudinaryField('image', default='placeholder')
    completed = models.IntegerField(choices=COMPLETED, default=0)

    def __str__(self):
        return self.name


class Carousel(models.Model):
    title = models.CharField(max_length=100)
    content = models.CharField(max_length=100)
    img_1 = CloudinaryField('image', default='placeholder')
    img_2 = CloudinaryField('image', default='placeholder')
    img_3 = CloudinaryField('image', default='placeholder')

    def __str__(self):
        return self.title

about/views.py
from django.shortcuts import render
from .models import About, Wainwright, Carousel
from django.views import View


class AboutView(View):
    def get(self, request):
        about = About.objects.first()
        carousel = Carousel.objects.all()[0]
        return render(request, 'about/about.html',
                      {
                          'about': about,
                          'carousel': carousel,
                      },
                      )


def wainwrights(request):
    wainwrights = Wainwright.objects.filter(completed=1)
    return render(request, 'about/wainwrights.html',
                  {
                          'wainwrights': wainwrights
                  }
                  )


def contact(request):
    return render(request, 'contact/contact.html',)

about/templates/about/about.html
{% extends 'base.html' %}
{% block content %}

<div id="myCarousel" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img class="first-slide img-fluid" src="{{ carousel.img_1.url }}" alt="First slide">
      <div class="container">
         <div class="carousel-caption translucent-bg">
           <h1>Routes</h1>
         </div>
      </div>
     </div>
    <div class="carousel-item">
      <img class="second-slide img-fluid" src="{{ carousel.img_2.url }}" alt="Second slide">
      <div class="container">
          <div class="carousel-caption translucent-bg">
            <h1>Photo Gallery</h1>
          </div>
      </div>
    </div>
    <div class="carousel-item">
      <img class="third-slide img-fluid" src="{{ carousel.img_3.url }}" alt="Third slide">
      <div class="container">
          <div class="carousel-caption translucent-bg">
            <h1>My Journey</h1>
          </div>
      </div>
    </div>
  </div>
  <a class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
<div class="main-body">
  <div class="row">
     <div class="col-lg-4 text-center">
       <a href="{% url 'routes:routes' %}">
         <div class="image-container">
           <img src="https://res.cloudinary.com/dpjdwg51y/image/upload/v1711655023/chf0akaasdgdt6t1wgkv.png" alt="Routes"
             width="140" height="140">
           <div class="overlay-text">
             <h2>Routes</h2>
             <p>My routes page is a guide to the tracks I've taken and sharing my personal experiences.</p>
           </div>
         </div>
       </a>
     </div>
     <div class="col-lg-4 text-center">
       <a href="{% url 'gallery:gallery' %}">
         <div class="image-container">
           <img src="https://res.cloudinary.com/dpjdwg51y/image/upload/v1711620403/gugcfmpumxduuv5hw0db.jpg"
             alt="Gallery" width="140" height="140">
           <div class="overlay-text">
             <h2>Gallery</h2>
             <p>The gallery page is a vibrant space where I and you can share hiking photos, capturing the beauty and
               spirit of the Lake District.</p>
           </div>
         </div>
       </a>
     </div>
     <div class="col-lg-4 text-center">
       <a href="{% url 'about:wainwrights' %}">
         <div class="image-container">
           <img src="https://res.cloudinary.com/dpjdwg51y/image/upload/v1711203023/p5zjackb05k3xmx0bv7s.jpg"
             alt="Wainwrights" width="140" height="140">
           <div class="overlay-text">
             <h2>Wainwrights</h2>
             <p>This page is dedicated to showcasing the Wainwrights I've completed, providing detailed information about
               each.</p>
           </div>
         </div>
       </a>
     </div>
  </div>
  <hr>
 </div>
 <div class="container about-me" id="my-journey">
  <div class="row">
     <div class="col-md-6">
       <img src="{{ about.profile_img.url }}" class="profile_img img-fluid" alt="{{ about.title }}">
     </div>
     <div class="col-md-6 journey-box">
       <h2>{{ about.title }}</h2>
       <br>
       <p>{{ about.content }}</p>
       <p>{{ about.updated_on }}</p>
       <p>{{ carousel.title }}</p>
       <a href="{% url 'contact:contact' %}" class="btn contact-me text-white">Contact Me</a>
     </div>
  </div>
 </div>
 <div class="container">
  <div class="row">
     <div class="col-12">
       <a href="#top" class="btn float-right rounded-circle page-top">
         <i class="fa fa-angle-up"></i>
       </a>
     </div>
  </div>
 </div>
 
{% endblock content %}

about/templates/about/wainwrights.html
{% extends 'base.html' %}

{% block content %}
 <div class="row ml-3 mr-3">
    <h1 class="text-center text-light completed-wainwrights">Completed Wainwrights</h1>
    <div class="row row-cols-1 row-cols-md-2 g-4">
      {% for wainwright in wainwrights %}
      <div class="col-md-3 mb-4">
          <div class="card wainwright-card">
              
                <img src="{{ wainwright.wainwright_img.url }}" class="img-fluid img-wainwright" alt="{{ wainwright.name }}">
        
              <div class="card-body">
                <h3>{{ wainwright.name }}</h3>
                <br>
                <p>{{ wainwright.description }}</p>
                <br>
                <p>Completed: {{ wainwright.get_completed_display }}</p>
              </div>
          </div>
      </div>
      {% endfor %}
    </div>
 </div> 
{% endblock %}